# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Project coverage MUST NOT drop below 70%
        target: 70%
        # Allow 1% fluctuation for environment variance
        threshold: 1%
        # Require at least this many lines to be covered
        if_ci_failed: error

    patch:
      default:
        # New code in PRs SHOULD have at least 70% coverage
        target: 70%
        # Allow 2% wiggle room on patches
        threshold: 2%

  # Fail CI if coverage drops by more than 2%
  changes:
    default:
      threshold: 2%
      if_not_found: success

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

parsers:
  go:
    partials_as_hits: true

ignore:
  - "cmd/**/*"  # Entry points have minimal logic
  - "**/*_test.go"
  - "**/testdata/**"
